### ISSUE TITLE
Not working on Linux (ubuntu 22.04)

### ISSUE THREAD

**Issue by axute** [frequency403/OpenSSH-GUI#3]
Just downloaded and started:

```
System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at OpenSSHALib.Lib.SettingsFileHandler.InitSettingsFile(String assemblyLocation, Boolean deleteBeforeInit)
Unhandled exception. System.ArgumentException: comment is not a valid enum member of OpenSSHALib.Enums.KeyType
   at OpenSSHALib.Models.SshKey..ctor(String absoluteFilePath)
   at OpenSSHALib.Models.SshPublicKey..ctor(String absoluteFilePath)
   at OpenSSHALib.Lib.DirectoryCrawler.<>c.<GetAllKeys>b__0_0(String e)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Collections.ObjectModel.ObservableCollection`1..ctor(IEnumerable`1 collection)
   at OpenSSHA_GUI.ViewModels.MainWindowViewModel..ctor()
   at OpenSSHA_GUI.App.OnFrameworkInitializationCompleted()
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at OpenSSHA_GUI.Program.Main(String[] args)
[1]    66863 IOT instruction (core dumped)  ./Downloads/OpenSSH-GUI-linux-x64.bin

```

**Comment by frequency403** [comment]
Hi, @axute! Thanks for submitting this issue. 

This problem was not known to me, and i fixed it already in the upcoming release of version 2.

 Please be patient for this, i will release the new version in this week!
